# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5bf57a4048155465d282263edcb190f46f09e4a210022b8b83c9827d75a638c75e49d9ba0c56017ab751c101979bacb5847fb30bdc1e75cf1b56ff5d188f96

test:
  secret_key_base: dddb7b8a8519e33b92ce21756ae7e50dd03fcbc1426557507d8a9d634887124398f9cb268fb056023bc93a529faa3139c1f0d607092a77caf7019d1e0d0f3600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
